[bell]
duration = 0

[env]
term = "xterm-256color"

[font]
size = 16

[font.bold]
family = "UDEV Gothic 35NFLG"
style = "Bold"

[font.normal]
family = "UDEV Gothic 35NFLG"
style = "Regular"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = 36
mods = "Command"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[shell]
args = ["-l", "-c", "zellij attach --index 0 --create"]
program = "/bin/zsh"

[window]
opacity = 0.9

[window.dimensions]
columns = 200
lines = 80

[window.padding]
x = 4
y = 4

[window.position]
x = 100
y = 200
