tap "dotenvx/brew"
tap "homebrew/bundle"
brew "openssl@3"
brew "bat"
brew "libyaml"
brew "cocoapods"
brew "fzf"
brew "gh"
brew "ghq"
brew "gibo"
brew "jq"
brew "lazygit"
brew "mas"
brew "mise"
brew "neovim"
brew "ripgrep"
brew "starship"
brew "zellij"
cask "1password"
cask "1password-cli"
cask "alacritty"
cask "android-sdk"
cask "android-studio"
cask "discord"
cask "docker"
cask "figma"
cask "font-hack-nerd-font"
cask "google-japanese-ime"
cask "grammarly-desktop"
cask "karabiner-elements"
cask "menubar-stats"
cask "microsoft-edge"
cask "obsidian"
cask "raycast"
cask "slack"
cask "spotify"
cask "temurin@8"
cask "visual-studio-code"
cask "warp"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 302584613
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
vscode "benjaminbenais.copilot-theme"
vscode "dart-code.dart-code"
vscode "dart-code.flutter"
vscode "dsznajder.es7-react-js-snippets"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "golang.go"
vscode "ms-azuretools.vscode-docker"
vscode "ms-vscode-remote.remote-containers"
vscode "redhat.java"
vscode "rust-lang.rust-analyzer"
vscode "tamasfe.even-better-toml"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
