# mise configuration for dotfiles repository
# This file is NOT managed by chezmoi to allow local customization

[tools]
shfmt = "latest"

[tasks.test]
description = "Run comprehensive dotfiles test suite"
run = "./scripts/test_comprehensive.sh"

[tasks.test-lazy]
description = "Test lazy loading system specifically"
run = "./tests/test_lazy_loading.sh"

[tasks.test-quick]
description = "Quick module loading test"
run = """
echo "Quick module test..."
zsh -c '
    source dot_config/zsh/modules/core/platform.zsh
    source dot_config/zsh/modules/core/core.zsh
    source dot_config/zsh/modules/tools/enhanced-lazy-tools.zsh
    source dot_config/zsh/modules/tools/lazy-loading.zsh
    
    echo "✓ Modules loaded successfully"
    type lazy_loading_stats >/dev/null && echo "✓ Lazy loading functions available"
    type detect_project_context >/dev/null && echo "✓ Project context detection available"
'
"""

[tasks.benchmark]
description = "Benchmark zsh startup time"
run = """
echo "Benchmarking startup (5 runs)..."
for i in {1..5}; do
    /usr/bin/time -p zsh -i -c exit 2>&1 | grep real | awk '{print $2}'
done | awk '{sum+=$1} END {printf "Average: %.3fs\\n", sum/NR}'
"""

[tasks.format]
description = "Format all files (MD with prettier, zsh with custom)"
run = """
pnpm run format:md
./scripts/format-zsh.sh -d dot_config/zsh -r
"""

[tasks.format-check]
description = "Check formatting without making changes"
run = "pnpm run format:check"

[tasks.format-md]
description = "Format only markdown files"
run = "pnpm run format:md"

[tasks.format-zsh]
description = "Format shell files using custom formatter"
run = "./scripts/format-zsh.sh -d dot_config/zsh -r"
