add_newline = false

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold green)"

[directory]
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "…/"

[hostname]
ssh_only = true
format = "[$hostname](bold red) "

[username]
style_user = "white bold"
disabled = false
show_always = true

[custom.arch]
command = "uname -m"
when = """ test $(uname -m) = "x86_64" """
style = "bold yellow"
format = "[$output]($style)"

[aws.region_aliases]
ap-northeast-1 = "Tokyo"
