## Atuin Configuration - Shell History Management
## Optimized for performance and usability

## UI Settings
style = "compact"
inline_height = 15
invert = true
show_preview = true
max_preview_height = 4
enter_accept = false

## Search and Filter Settings
search_mode = "fuzzy"
filter_mode = "global"
exit_mode = "return-original"

## Sync Settings
auto_sync = true
sync_frequency = "5m"

## Performance Settings
network_connect_timeout = 5
network_timeout = 5
local_timeout = 5

## Security
secrets_filter = true

## Statistics Configuration
[stats]
common_subcommands = [
  "git",
  "docker",
  "kubectl",
  "npm",
  "pnpm",
  "cargo",
  "go",
  "chezmoi",
]

common_prefix = ["sudo"]

ignored_commands = [
  "cd",
  "ls",
  "ll",
  "la",
  "pwd",
  "clear",
]

## Sync v2 Configuration
[sync]
records = true

## Preview Configuration
[preview]
strategy = "auto"
