# mise configuration file
# https://mise.jdx.dev/configuration.html

[settings]
# Use XDG directories
experimental = true
asdf_compat = false
# Automatically load .env files in directories
env_file = ".env"

[tools]
# Define default tool versions
# Use mise to manage Rust instead of rustup
rust = "stable"

# Other runtime versions can be defined here
ruby = "latest"
node = "lts"
go   = "latest"
# python = "3.12"

ghq  = "latest"
lazydocker = "latest"
usage = "latest"

# relatively npm packages in global
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"

