# Lazygit設定ファイル（クリーン版）
# コメントアウトされた不要な行を削除し、整理された状態

gui:
  # テーマ設定
  theme:
    activeBorderColor:
      - '#8be9fd'
      - bold
    inactiveBorderColor:
      - '#44475a'
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
    cherryPickedCommitBgColor:
      - blue
    cherryPickedCommitFgColor:
      - cyan
    unstagedChangesColor:
      - red
      
  # 表示設定
  showFileTree: true
  showListFooter: true
  showRandomTip: false
  showBranchCommitHash: false
  showBottomLine: true
  showPanelJumps: true
  
  # レイアウト
  nerdFontsVersion: ""
  commitLength:
    show: true
  mouseEvents: true
  skipDiscardChangeWarning: false
  skipStashWarning: false
  showFileTree: true
  showListFooter: true
  showRandomTip: false
  
  # 言語設定
  language: "auto"

# Git設定
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  commit:
    signOff: false
    verbose: default
  merging:
    manualCommit: false
    args: ""
  mainBranches:
    - master
    - main
  skipHookPrefix: WIP
  autoFetch: true
  autoRefresh: true
  branchLogCmd: "git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
  allBranchesLogCmd: "git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --all"
  overrideGpg: false
  disableForcePushing: false

# キーバインディング
keybinding:
  universal:
    quit: 'q'
    quit-alt1: '<c-c>'
    return: '<esc>'
    quitWithoutChangingDirectory: 'Q'
    togglePanel: '<tab>'
    prevItem: '<up>'
    nextItem: '<down>'
    prevItem-alt: 'k'
    nextItem-alt: 'j'
    prevPage: ','
    nextPage: '.'
    scrollLeft: 'H'
    scrollRight: 'L'
    gotoTop: '<'
    gotoBottom: '>'
    toggleRangeSelect: 'v'
    rangeSelectDown: '<s-down>'
    rangeSelectUp: '<s-up>'
    prevBlock: '<left>'
    nextBlock: '<right>'
    prevBlock-alt: 'h'
    nextBlock-alt: 'l'
    nextBlock-alt2: '<tab>'
    prevBlock-alt2: '<backtab>'
    jumpToBlock: ['1', '2', '3', '4', '5']
    nextMatch: 'n'
    prevMatch: 'N'
    startSearch: '/'
    optionMenu: null
    optionMenu-alt1: '?'
    select: '<space>'
    goInto: '<enter>'
    confirm: '<enter>'
    confirmInEditor: '<a-enter>'
    remove: 'd'
    new: 'n'
    edit: 'e'
    openFile: 'o'
    scrollUpMain: '<pgup>'
    scrollDownMain: '<pgdown>'
    scrollUpMain-alt1: 'K'
    scrollDownMain-alt1: 'J'
    scrollUpMain-alt2: '<c-u>'
    scrollDownMain-alt2: '<c-d>'
    executeCustomCommand: ':'
    createRebaseOptionsMenu: 'm'

# 更新設定
update:
  method: prompt
  days: 14

# リフレッシュ設定
refresher:
  refreshInterval: 10
  fetchInterval: 60

# 通知設定
notARepository: 'prompt'