name: Test Chezmoi Migration

on:
  push:
    branches: [chezmoi-migration]
  pull_request:
    branches: [chezmoi-migration]

env:
  CHEZMOI_VERSION: "2.36.1"

jobs:
  test-chezmoi:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, macos-12, macos-13]
        scenario: [fresh, update, minimal]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install chezmoi
      run: |
        if [[ "${{ matrix.os }}" == "ubuntu"* ]]; then
          sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH
        else
          brew install chezmoi
        fi
        
    - name: Test chezmoi init (fresh install)
      if: matrix.scenario == 'fresh'
      run: |
        chezmoi init --apply --verbose
        
    - name: Test shell functionality
      run: |
        zsh -c "echo 'Shell test passed'"
        
    - name: Performance benchmark
      run: |
        echo "=== Startup Time Benchmark ==="
        for i in {1..5}; do
          /usr/bin/time -p zsh -i -c 'exit' 2>&1 | grep real
        done
        
    - name: Feature verification
      run: |
        tests/verify_features.sh
        
    - name: Cross-platform compatibility check
      run: |
        tests/check_compatibility.sh ${{ matrix.os }}